/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appalquilerveh.vehiculo;

import appalquilerveh.dao.VehiculoDao;
import appalquilerveh.logica.Vehiculo;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jbermudezb
 */
public class frmVehiculo extends javax.swing.JInternalFrame {

    // variables para gestionar los metodos a la base de datos HUELLAS
    //static Metodos logica = new Metodos();
    static VehiculoDao vdao = new VehiculoDao();
    
    /**
     * Creates new form Vehiculo
     */
    public frmVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtmat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboti = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnen = new javax.swing.JButton();
        txtdesc = new javax.swing.JTextField();
        btnCan = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setTitle("Crear Vehiculo");

        jLabel1.setText("Matricula");

        jLabel2.setText("Tipo de Vehiculo");

        cboti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coche", "MicroBuses", "Furgoneta de Carga", "Camion de Carga", " " }));

        jLabel3.setText("Descripcion");

        btnen.setText("Enviar");
        btnen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenActionPerformed(evt);
            }
        });

        btnCan.setText("Cerrar");
        btnCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtmat))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cboti, 0, 279, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCan)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtdesc))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnen)
                    .addComponent(btnCan)
                    .addComponent(btnModificar))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenActionPerformed
        // TODO add your handling code here:
        
        Vehiculo v = new Vehiculo();
        v.setMatricula(txtmat.getText().toUpperCase());
        v.setTipo(cboti.getSelectedItem().toString());
        v.setDescripcion(txtdesc.getText().toUpperCase());
        
        try {
            //if (!vdao.existeVehiculo(v.getMatricula())) {
            if (!vdao.existe(v.getMatricula())) {
                //logica.guardarVehiculo(v);
                vdao.guardar(v);
                JOptionPane.showMessageDialog(this, "Vehiculo agregado correctamente", "Crear", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Vehiculo existe", "Crear", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IllegalStateException ex) {
            Logger.getLogger(frmVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(frmVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnenActionPerformed

    private void btnCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanActionPerformed
        // TODO add your handling code here:
        this.dispose(); // cerrar ventana
    }//GEN-LAST:event_btnCanActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        try {
            Vehiculo v = new Vehiculo();

            v.setMatricula(txtmat.getText().toUpperCase() );
            v.setTipo(cboti.getSelectedItem().toString() );
            v.setDescripcion(txtdesc.getText().toUpperCase() );
            
            //logica.modificarVehiculo(v);
            vdao.modificar(v);
            JOptionPane.showMessageDialog(this, "Vehiculo modificado correctamente", "Modificar", JOptionPane.INFORMATION_MESSAGE);

        } catch (IllegalStateException ex) {
            Logger.getLogger(frmVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(frmVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCan;
    public static javax.swing.JButton btnModificar;
    public static javax.swing.JButton btnen;
    public javax.swing.JComboBox<String> cboti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JTextField txtdesc;
    public javax.swing.JTextField txtmat;
    // End of variables declaration//GEN-END:variables
}
