/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appalquilerveh.alquiler;

import appalquilerveh.dao.AlquilerDao;
import appalquilerveh.dao.VehiculoDao;
import appalquilerveh.logica.Alquiler;
import appalquilerveh.logica.Combo;
import appalquilerveh.logica.Vehiculo;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jbermudezb
 */
public class frmAlquiler extends javax.swing.JInternalFrame {

    // variables para gestionar los metodos a la base de datos HUELLAS
    //static Metodos logica = new Metodos();
    static AlquilerDao adao = new AlquilerDao();
    static VehiculoDao vdao= new VehiculoDao();

    /**
     * Creates new form Alquiler
     */
    public frmAlquiler() throws Exception {
        initComponents();
        this.llenarcboVehiculo();
    }

    public void llenarcboVehiculo() throws NoSuchAlgorithmException, Exception {
        cbove.removeAllItems();
        List<Vehiculo> l = new LinkedList<Vehiculo>();
        l = vdao.listar();
        for (int i = 0; i < l.size(); i++) {
            cbove.addItem(new Combo(l.get(i).getIdvehiculo(), l.get(i).getMatricula() + " " + l.get(i).getTipo()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtnro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbove = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtdi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        btnen = new javax.swing.JButton();
        btnCan = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setTitle("Crear Alquiler");

        jLabel1.setText("Nro Orden");

        jLabel2.setText("Vehiculo");

        jLabel3.setText("Nro Dias");

        jLabel4.setText("Nombre Contacto");

        jLabel5.setText("Telefono Contacto");

        btnen.setText("Enviar");
        btnen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenActionPerformed(evt);
            }
        });

        btnCan.setText("Cerrar");
        btnCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE))
                    .addComponent(txtnro)
                    .addComponent(cbove, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtdi)
                    .addComponent(txtnom)
                    .addComponent(txttel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnen)
                    .addComponent(btnCan)
                    .addComponent(btnModificar))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenActionPerformed
        // TODO add your handling code here:

        Alquiler a = new Alquiler();
        a.setNroorden(Integer.parseInt(txtnro.getText()));
        a.setNombrePersona(txtnom.getText().toUpperCase());
        a.setContactoPersona(txttel.getText());
        a.setDia(Integer.parseInt(txtdi.getText()));

        try {
            Vehiculo v = adao.consultarVehiculo(cbove.getItemAt(cbove.getSelectedIndex()).getIdCombo());
            a.setVehiculo(v.getIdvehiculo());
            switch (v.getTipo()) {
                case "Coche":
                    double precio_coche = 1.5;
                    a.setPrecioAlquiler(a.getBase() + (precio_coche * a.getDia()));
                    break;
                case "MicroBuses":
                    double precio_MicroBuses = 2;
                    a.setPrecioAlquiler(a.getBase() + (precio_MicroBuses * a.getDia()));
                    break;
                case "Furgoneta de Carga":
                    a.setPma(Integer.parseInt(JOptionPane.showInputDialog("Introduzca un PMA (Peso Maximo Autorizado en Toneladas)")));
                    double precio_cargaMin = a.getBase() + 20;
                    a.setPrecioAlquiler(precio_cargaMin * a.getPma() * a.getDia());
                    break;
                case "Camion de Carga":
                    a.setPma(Integer.parseInt(JOptionPane.showInputDialog("Introduzca un PMA (Peso Maximo Autorizado en Toneladas)")));
                    double precio_cargaMax = a.getBase() + 40;
                    a.setPrecioAlquiler(precio_cargaMax * a.getPma() * a.getDia());
                    break;

            }

            //if (!adao.existeAlquiler(a.getNroorden())) {
            if (!adao.existe(String.valueOf(a.getNroorden())) ) {
                //logica.guardarAlquiler(a);
                adao.guardar(a);
                JOptionPane.showMessageDialog(this, "Alquiler agregado correctamente", "Crear", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Alquiler existe", "Crear", JOptionPane.ERROR_MESSAGE);
            }

        } catch (IOException ex) {
            Logger.getLogger(frmAlquiler.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalStateException ex) {
            Logger.getLogger(frmAlquiler.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(frmAlquiler.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(frmAlquiler.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnenActionPerformed

    private void btnCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanActionPerformed
        // TODO add your handling code here:
        this.dispose(); // cerrar ventana
    }//GEN-LAST:event_btnCanActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        try {
            Alquiler a = new Alquiler();

            a.setNroorden(Integer.parseInt(txtnro.getText()));
            a.setNombrePersona(txtnom.getText().toUpperCase());
            a.setContactoPersona(txttel.getText());

            if (a.getDia() != Integer.parseInt(txtdi.getText())) {
                a.setDia(Integer.parseInt(txtdi.getText()));
                // proceso de recalculo de precio si el dia cambia
                try {
                    Vehiculo v = adao.consultarVehiculo(cbove.getItemAt(cbove.getSelectedIndex()).getIdCombo());
                    a.setVehiculo(v.getIdvehiculo());
                    switch (v.getTipo()) {
                        case "Coche":
                            double precio_coche = 1.5;
                            a.setPrecioAlquiler(a.getBase() + (precio_coche * a.getDia()));
                            break;
                        case "MicroBuses":
                            double precio_MicroBuses = 2;
                            a.setPrecioAlquiler(a.getBase() + (precio_MicroBuses * a.getDia()));
                            break;
                        case "Furgoneta de Carga":
                            a.setPma(Integer.parseInt(JOptionPane.showInputDialog("Introduzca un PMA (Peso Maximo Autorizado en Toneladas)")));
                            double precio_cargaMin = a.getBase() + 20;
                            a.setPrecioAlquiler(precio_cargaMin * a.getPma() * a.getDia());
                            break;
                        case "Camion de Carga":
                            a.setPma(Integer.parseInt(JOptionPane.showInputDialog("Introduzca un PMA (Peso Maximo Autorizado en Toneladas)")));
                            double precio_cargaMax = a.getBase() + 40;
                            a.setPrecioAlquiler(precio_cargaMax * a.getPma() * a.getDia());
                            break;

                    }

                    //logica.modificarAlquiler(a);
                    adao.modificar(a);
                    JOptionPane.showMessageDialog(this, "Alquier modificado correctamente", "Modificar", JOptionPane.INFORMATION_MESSAGE);

                } catch (IOException ex) {
                    Logger.getLogger(frmAlquiler.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalStateException ex) {
                    Logger.getLogger(frmAlquiler.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NoSuchAlgorithmException ex) {
                    Logger.getLogger(frmAlquiler.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(frmAlquiler.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                a.setDia(Integer.parseInt(txtdi.getText()));
                //logica.modificarAlquiler(a);
                adao.modificar(a);
                JOptionPane.showMessageDialog(this, "Alquier modificado correctamente", "Modificar", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (IllegalStateException ex) {
            Logger.getLogger(frmAlquiler.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(frmAlquiler.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCan;
    public static javax.swing.JButton btnModificar;
    public static javax.swing.JButton btnen;
    public javax.swing.JComboBox<Combo> cbove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JTextField txtdi;
    public javax.swing.JTextField txtnom;
    public javax.swing.JTextField txtnro;
    public javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
