/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appalquilerveh.alquiler;

import appalquilerveh.dao.Metodos;
import appalquilerveh.logica.Alquiler;
import appalquilerveh.logica.Combo;
import appalquilerveh.logica.Vehiculo;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jbermudezb
 */
public class frmAlquiler extends javax.swing.JInternalFrame {

    // variables para gestionar los metodos a la base de datos HUELLAS
    static Metodos logica = new Metodos();

    /**
     * Creates new form Alquiler
     */
    public frmAlquiler() throws Exception {
        initComponents();
        this.llenarcboVehiculo();
    }

    public void llenarcboVehiculo() throws NoSuchAlgorithmException, Exception {
        cbove.removeAllItems();
        try {
            List<Vehiculo> l = new LinkedList<Vehiculo>();
            l = logica.listarTodosVehiculos();
            for (int i = 0; i < l.size(); i++) {
                cbove.addItem(new Combo(l.get(i).getIdvehiculo(), l.get(i).getMatricula() + " " + l.get(i).getTipo()));
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmAlquiler.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(frmAlquiler.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtnro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbove = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtdi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnCan = new javax.swing.JButton();

        setTitle("Crear Alquiler");

        jLabel1.setText("Nro Orden");

        jLabel2.setText("Vehiculo");

        jLabel3.setText("Nro Dias");

        jLabel4.setText("Nombre Contacto");

        jLabel5.setText("Telefono Contacto");

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCan.setText("Cerrar");
        btnCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCan)
                        .addGap(0, 121, Short.MAX_VALUE))
                    .addComponent(txtnro)
                    .addComponent(cbove, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtdi)
                    .addComponent(txtnom)
                    .addComponent(txttel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnCan))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Alquiler a = new Alquiler();
        a.setNroorden(Integer.parseInt(txtnro.getText()));
        a.setNombrePersona(txtnom.getText().toUpperCase());
        a.setContactoPersona(txttel.getText());
        a.setDia(Integer.parseInt(txtdi.getText()));

        try {
            Vehiculo v = logica.consultarVehiculo(cbove.getItemAt(cbove.getSelectedIndex()).getIdCombo());
            switch (v.getTipo()) {
                case "Coche":
                    double precio_coche = 1.5;
                    a.setPrecioAlquiler(a.getBase() + (precio_coche * a.getDia()));
                    break;
                case "MicroBuses":
                    double precio_MicroBuses = 2;
                    a.setPrecioAlquiler(a.getBase() + (precio_MicroBuses * a.getDia()));
                    break;
                case "Furgoneta de Carga":
                    a.setPma(Integer.parseInt(JOptionPane.showInputDialog("Introduzca un PMA (Peso Maximo Autorizado en Toneladas)")));
                    double precio_cargaMin = a.getBase() + 20;
                    a.setPrecioAlquiler(precio_cargaMin * a.getPma() * a.getDia());
                    break;
                case "Camion de Carga":
                    double precio_cargaMax = 40;
                    a.setPrecioAlquiler(precio_cargaMax * a.getDia());
                    break;

            }
            logica.guardarAlquiler(a);
        } catch (IOException ex) {
            Logger.getLogger(frmAlquiler.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalStateException ex) {
            Logger.getLogger(frmAlquiler.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(frmAlquiler.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(frmAlquiler.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanActionPerformed
        // TODO add your handling code here:
        this.dispose(); // cerrar ventana
    }//GEN-LAST:event_btnCanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCan;
    private javax.swing.JComboBox<Combo> cbove;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtdi;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtnro;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
